services:
  msinit-frontend-service:
    build: .
    networks:
      - msinit-network
    ports:
      - "8080:80"
    container_name: msinit-frontend-service
networks:
  msinit-network:
    external: true