services:
  msinit-frontend:
    build:
      context: .
      args:
        - VITE_API_URL: ${VITE_API_URL}
    networks:
      - msinit-network
      - shared-network
    ports:
      - "3001:80"
    container_name: msinit-frontend
networks:
  msinit-network:
    external: true
  shared-network:
    external: true
